include ./../makepre

LIB_INCLUDES+= -I./
LIB_NAME=tcode.transport
LIB_SRCS=event_loop.cpp\
	event_timer.cpp\
	event_timer.cpp\
	tcp/acceptor.cpp\
	tcp/acceptor_handler.cpp\
	tcp/channel.cpp\
	tcp/channel_config.cpp\
	tcp/connector.cpp\
	tcp/connector_handler.cpp\
	tcp/filter.cpp\
	tcp/packet_buffer.cpp\
	tcp/pipeline.cpp\
	tcp/filters/size_filter.cpp\
	tcp/filters/timeout_filter.cpp\
	udp/bootstrap.cpp\
	udp/channel.cpp\
	udp/pipeline.cpp\
	udp/filter.cpp\
	
include ./../makepost