include ./../makepre

LIB_NAME=tcode.common
LIB_SRCS=lib_allocator.cpp\
time_span.cpp\
time_stamp.cpp\
time_util.cpp\
rtti.cpp\
string.cpp\

ifdef SHARED_LIB
MAJOR_VER=1
MINOR_VER=0
endif

include ./../makepost