include ./../makepre

LIB_CPPFLAGS+= -I./
LIB_NAME=tcode.diagnostics
LIB_SRCS=	tcode_error_code.cpp\
			tcode_category_impl.cpp\
			posix_category_impl.cpp\
			last_error.cpp\
			log/record.cpp\
			log/logger.cpp\
			log/writer.cpp\
			log/formatter.cpp\
			log/console_writer.cpp\
			log/file_writer.cpp\

include ./../makepost